name: Publish to PyPI  # Name of your workflow

on:
  release:
    types: [created]  # Trigger the workflow when a release is created

permissions:
  contents: read       # Allows reading repository contents
  packages: write      # Allows publishing packages to PyPI
  id-token: write      # Allows accessing the OIDC token

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI using Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          package_dir: dist
          use_trusted_publisher: true  # Enables OIDC authentication
